[phases.setup]
nixPkgs = ["python312", "gcc", "postgresql_16"]

[phases.install]
cmds = [
  "pip install -r requirements.txt -r requirements-postgres.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/app/entrypoint.sh"
